version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - network.host=0.0.0.0
    networks:
      - esnet

  db:
    image: postgres:16.10
    container_name: ecommerce_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: Niffier2025
      POSTGRES_DB: ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - esnet

  redis:
    image: redis:7.2
    container_name: ecommerce_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:

networks:
  esnet:
    driver: bridge
