"""add_oauth_fields

Revision ID: 3ad9ba346a41
Revises: 
Create Date: 2025-09-04 11:49:28.363645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ad9ba346a41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('oauth_id', sa.String(length=100), nullable=True, server_default="null"))
    op.add_column('users', sa.Column('profile_picture', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('is_oauth_user', sa.Boolean(), nullable=False, server_default="false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_oauth_user')
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'oauth_id')
    op.drop_column('users', 'oauth_provider')
    # ### end Alembic commands ###
